### ISSUE TITLE
Issue with setup

### ISSUE THREAD

**Issue by blackbeard718** [ChatTheatre/gables_game#2]
Hello! I'm very new to this and that's probably not the best place to start, but I've played Castle Marrach for about 10 years consistently and am currently a StoryBuilder for game. I got the inkling to try and set up a game I had an idea for and found my way here. I've gotten most of it set up correctly (I think) and am hung up on the following error I keep getting:

`Failed authorization procedure. gables.thaetia.com (http-01): urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for gables.thaetia.com - check that a DNS record exists for this domain
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: gables.thaetia.com
   Type:   None
   Detail: DNS problem: NXDOMAIN looking up A for gables.thaetia.com -
   check that a DNS record exists for this domain
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
`

I'm running into an issue with correctly setting up the DNS and not sure exactly what I'm supposed to be inputting and where. I own the domain name "www.thaetia.com" but not entirely sure what to do with it from there. Any guidance would be greatly appreciated.

**Comment by noahgibbs** [comment]
This looks like you'll need to set up a DNS entry for gables.thaetia.com. Did you try to do that and it didn't work, or do you need help with how to do it? You'll want to get the numeric IP address for your new server, for starters - that's going to be the IP for the new DNS entry.

**Comment by noahgibbs** [comment]
Also, how are you hosting it? Linode, existing server or something else?

**Comment by blackbeard718** [comment]
I think I tried set up the DNS entry, but may have done it incorrectly. I've tried several different variations to get it to work prior to submitting an issue, so I've lost track on what I've done lol. I've never set up DNS entries, let alone on Linode, so I'm sure I'm just doing something in the wrong spot, so was hoping for a little more guidance on that particular step.

I am hosting on Linode currently and pulled the Gables StackScript to set it up with.

**Comment by blackbeard718** [comment]
As of now, I've deleted everything in order to start from scratch with a new Linode build. Only step taken is adding the gables StackScript.

**Comment by ChristopherA** [comment]
Welcome!

I’d also suggest you talk and maybe schedule a walk-through with Sarah Tackett  @saraht45 — we would love to get more storybuilders involved as it helps for the long-term stability of our games to spread the knowledge!

— Christopher Allen

**Comment by saraht45** [comment]
Hi there.. Happy to help if I can. I believe I received that error during my initial setup and was definitely related to DNS issues. I can send you a screenshot of my DNS settings if you think that will help.

**Comment by blackbeard718** [comment]
> Hi there.. Happy to help if I can. I believe I received that error during my initial setup and was definitely related to DNS issues. I can send you a screenshot of my DNS settings if you think that will help.

@saraht45  - I think that would help tremendously. If I can just see the area I should be working in, I think I can get back on track. 

@ChristopherA  - Once Sarah helps me figure things out, I would be happy to pass along what I know to other staffers who might show interest in it so we all have a better understanding of the Engine and game from the ground up.

**Comment by noahgibbs** [comment]
Sounds like at a minimum we should add screenshots of setting up DNS on Linode to our setup guide.

**Comment by saraht45** [comment]
Here is the screenshot of my settings. Hopefully it helps. 

![Screenshot_20211017-171316_Chrome](https://user-images.githubusercontent.com/37392018/137645299-916389ad-17a5-4755-954d-d344cc182e0c.jpg)

**Comment by blackbeard718** [comment]
That does help. Follow-up question based on those settings. At least for Linode, when setting up based on the Gables StackScript, do I need to include "game." like in the example? Or should it just be thaetia.com, if that's my domain name?

![Screen Shot 2021-10-17 at 5 30 16 PM](https://user-images.githubusercontent.com/76076691/137645659-cce9e7e3-a77a-4bb3-a487-ed5519c6e03c.png)

**Comment by noahgibbs** [comment]
You don't need "game" for that one, but you need both "gables" (the game client) and "gables-login" (the login server.)

(Edited, much later: I misunderstood. No "game." in the box, no. And what I wrote above was for DNS entries to set up, which is a different question.)

**Comment by saraht45** [comment]
I believe you just need to put thaetia.com in that box.

**Comment by blackbeard718** [comment]
Great! And for setting up the DNS records (again, specific to Linode) is this the right area and what I should be inputting for "gables"?
![Screen Shot 2021-10-17 at 7 48 17 PM](https://user-images.githubusercontent.com/76076691/137649408-91c09eaa-0b75-4a7f-ab94-8a5d5395b3f8.png)

**Comment by noahgibbs** [comment]
Look like, yeah.

**Comment by blackbeard718** [comment]
Yeah, I'm still encountering the same error. I've got them plugged in here, but the interesting thing is that it removes the subdomain when I select "create"
![Screen Shot 2021-10-17 at 8 59 49 PM](https://user-images.githubusercontent.com/76076691/137652108-5482243c-9683-4cfa-9390-d4fa1a215ddc.png)
.

**Comment by noahgibbs** [comment]
That looks reasonable, assuming the IP address is right. I'm not able to connect to that URL, though - Chrome is acting as though there's no DNS entry for it :-/

I'm assuming that you've registered Linode's DNS servers with your domain registrar as the ones you're using?

**Comment by blackbeard718** [comment]
If I'm being honest, I doubt I've done that, since I'm not entirely sure what all that entails. Do you mean like this?
![Screen Shot 2021-10-19 at 10 37 06 AM](https://user-images.githubusercontent.com/76076691/137932834-c1161946-929d-4cc3-a585-9c9018e173df.png)

**Comment by blackbeard718** [comment]
I got passed that step! 

Issue was I was working in the "Domains" section in Linode, not my domain registrar.

**Comment by noahgibbs** [comment]
The one.com thing was the one I meant, yeah. If one.com thought you weren't using the Linode nameservers then it wouldn't matter what you told Linode to put in them :-)

**Comment by noahgibbs** [comment]
Can you edit the Linode entries and make sure that when you edit them, they only say "gables" and "gables-login", not "gables.thaetia.com" and "gables-login.thaetia.com"? That's what they *should* say. The Linode table you screenshotted above *looks* good, but obviously there's no DNS entry happening :-(

**Comment by blackbeard718** [comment]
So for clarification's sake: 

I need to register entries with my domain registrar as pictured below![image](https://user-images.githubusercontent.com/76076691/137989380-c2271a6a-0185-4aa1-b1a4-f4d7f077802b.jpeg)

Do I also need to add those entries to the domain section on Linode?

Lastly, do I then need to add the name servers from linode onto my domain registrar as well?

I was able to access gables-login.thaetia.online (went with a different domain) and actually log in and mess around a bit. Just want to make sure I'm doing it all correctly

**Comment by noahgibbs** [comment]
There are two approaches, both of which can work:

* You can tell your domain registrar to use Linode for DNS, then tell Linode to register those entries

Or...

* You can directly add those entries to your domain registrar.

It's just weird that you tried option one and it didn't seem to work :-/ Normally you'll want to create a Linode and then immediately register the name, which allows you to do everything in one go -- start up the game, set up LetsEncrypt for HTTPS, etc. It's also possible to update an existing server, but that can be more complicated.

**Comment by blackbeard718** [comment]
From how you described it, it sounds like I did it out of order. I'll give the first method another go in the correct order since I at least know what method two looks like if I need to fall back on it.

**Comment by noahgibbs** [comment]
The order shouldn't matter for the first way, but you *do* have to wait a bit (between an hour and about a day) for DNS entries to change. You'll probably also want to clear your local DNS cache so that you're seeing the same thing other people would.

**Comment by blackbeard718** [comment]
Okay, I gave it about 20 hours and just tried again. It seemed to run through the setup process correctly. Now upon navigating to www.thaetia.online, I'm getting a "Privacy Error" on my browser. Is there a way to fix this:

**This server could not prove that it is www.thaetia.online; its security certificate is from meet.thaetia.online. This may be caused by a misconfiguration or an attacker intercepting your connection.**

**Comment by saraht45** [comment]
I'm getting a "Site cannot be reached" error when trying to navigate to www.thaetia.online. 

I'm going to run through the setup again on my server to refresh my memory on the process. Hopefully tonight or tomorrow, and I will screen shot what my settings are in Linode, one.com, and stackscript. We will get this sorted out :) If a voice call or text is an easier way to communicate to get through troubleshooting, let me know. Happy to do either.

**Comment by blackbeard718** [comment]
I appreciate it! I'm sure I'm just missing some minor step in the process, so I'll take my mind off of it until you're able to post again. Please don't rush on my account!

**Comment by noahgibbs** [comment]
For starters, the setup scripts are *only* going to put certs in place for the domain you gave (thaetia.com, yes?) and not any others (like thaetia.online). Basically there will only be correct SSL certs for gables.thaetia.com, gables-login.thaetia.com and meet.thaetia.com. Anything else you want, you'll have to set up for yourself. Definitely possible to add more, but the StackScript only knows the one you told it.

**Comment by blackbeard718** [comment]
Initially I went with thaetia.com, but opted to go with the thaetia.online domain a few days later. I started the linode process from scratch after making that change and was still running into the errors.

One question I probably should have asked earlier, do I have to change anything within the actual StackScript? I was under the impression that it would be a plug and play situation when inputting that for the linode server, but I'm probably mistaken.

**Comment by noahgibbs** [comment]
You shouldn't normally need to change the StackScript, just provide it different parameters. You may need/want to change something if you want something it doesn't do (e.g. more subdomains than the SkotOS ones.)

**Comment by saraht45** [comment]
No changes need to be made to the stackscript.

I rebuilt my server using the stackscript and these are my settings:
<img width="941" alt="linode stackscript settings 1" src="https://user-images.githubusercontent.com/37392018/138538434-cf1f3529-88d2-4a3b-a675-c940a155049a.png">
<img width="944" alt="linode stackscript settings 2" src="https://user-images.githubusercontent.com/37392018/138538439-26a2bc4c-5036-4331-95d3-b454e777a0f5.png">

It took about 10-15 minutes for the rebuild and game initialization to complete. Once finished, I could login with the url https://gables-login.autonify.net/

**Comment by blackbeard718** [comment]
Giving it another shot based on the above, I noticed my initial settings are different than the above settings. Could that be anything that's causing a problem?

![Screen Shot 2021-10-24 at 7 33 43 PM](https://user-images.githubusercontent.com/76076691/138617324-12d65ffa-279e-4d92-9f8f-ddee3797a486.png)

**Comment by saraht45** [comment]
I wonder if the StackScript has changed. We should compare the one I have saved vs the one you are using.

**Comment by blackbeard718** [comment]
I'm using the one that comes from [here](https://github.com/ChatTheatre/gables_game/blob/master/deploy_scripts/stackscript/gables_stackscript.sh) if that helps.

**Comment by noahgibbs** [comment]
It looks like you're using latest -- should be great. If anything, it looks like Sarah may be using a slightly-outdated (but probably just fine) Gables StackScript, which still downloads the latest SkotOS StackScript when it runs.

**Comment by blackbeard718** [comment]
I'm starting to feel like I may not be cut out for this as I'm hitting another wall:

`Last login: Tue Oct 26 01:12:32 2021 from 100.16.207.196
root@gables:~# tail -f game_standup.log
Obtaining a new certificate
An unexpected error occurred:
There were too many requests of a given type :: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: gables.thaetia.online: see https://letsencrypt.org/docs/rate-limits/
Please see the logfiles in /var/log/letsencrypt for more details.`

I actually got this for the first time almost exactly a week ago, so I gave it some time and took a break to see if I could come back to it fresh, but I'm still getting this error. I'm not sure of the process to clear out the certificates, or if I need to wait until tomorrow so that a full week has passed, but if anyone is familiar with this, I'd appreciate some assistance so I can go back to my first set of problems lol.
